### ISSUE TITLE
Add Tier 1 and Tier 2 Categories 

### ISSUE THREAD

**Issue by paulhollmann** [VATGER-Nav/datahub#14]
For the new GCAP there need to be a classification of the station.
Either none,
Tier 1,
or Tier 2 "Group XY"

**Comment by fsoest** [comment]
We also need a classification for training airports.

**Comment by LeoKle** [comment]
`
{
  "gcap_class": 0 | 1 | 2,
  "gcap_class2_type": "AFIS" | "MIL TWR" | "MIL APP",
  "gcap_training_aiport": true | false
}
`

we can also shorten it to the following, if you'd like:

`
{
  "gcap_class": 0 | 1 | "AFIS" | "MIL TWR" | "MIL APP",
  "gcap_training_aiport": true | false
}
`

**Comment by paulhollmann** [comment]
> { "gcap_class": 0 | 1 | "AFIS" | "MIL TWR" | "MIL APP", "gcap_training_aiport": true | false }

yes we can do that, also with `gcap_class` as an optional field (so default is `0`)

**Comment by fpletz** [comment]
IMHO using only strings for `gcap_class` is nicer so it can be just a plain string type in the corresponding schema.

```{ "gcap_class": "0" | "1" | "AFIS" | "MIL TWR" | "MIL APP", "gcap_training_aiport": true | false }```

**Comment by LeoKle** [comment]
We agreed verbally to the following

`{ "gcap_class": "0" | "1" | "AFIS" | "MIL TWR" | "MIL APP", "gcap_training_aiport": true }`
with `gcap_training_aiport = false` as default if the property does not exists
