### ISSUE TITLE
EDMM Booking schedules

### ISSUE THREAD

**Issue by jannikvogel** [VATGER-Nav/datahub#80]
Stations for EDDM and EDDP are wanted in the rythm: EDDM, EDDM, EDDP, EDDM, EDDM, EDDP, ... [2 times EDDM, 1 time EDDP]
Stations for EDDN remain wanted every Monday

I do not see a way to reflect the current EDDM/DP rythm, anyone able to help me? 
@LeoKle @paulhollmann

**Comment by paulhollmann** [comment]
Da sich das ja alle 21 Tage wiederholt, machst du zB
Alle 21 Tage München ab Datum Mittwoch 2.10.
Alle 21 Tage München ab Datum Mittwoch 9.10.
Alle 21 Tage Leipzig ab Datum Mittwoch 16.10.

Man muss jetzt halt EDDM zweimal eintragen, aber mit Copy Pasta geht das ja ganz schnell

**Comment by jannikvogel** [comment]
Danke
